%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/autorun/Documents/rashid/en.sahih.csv
%
% Auto-generated by MATLAB on 28-Oct-2020 21:39:23

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "|";

% Specify column names and types
opts.VariableNames = ["ayah", "verse", "text"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "text", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "text", "EmptyFieldRule", "auto");

% Import the data
quran_table = readtable("/home/autorun/Documents/rashid/en.sahih.csv", opts);


%% Clear temporary variables
clear opts

quran_cell= table2cell(quran_table);


strfind(quran_table{1:3,3},'Entirely Merciful')

quran_array={};
for ii=1:height(quran_table)
    ayah=quran_table{ii,1};
    verse=quran_table{ii,2};
    quran_array{ayah}{verse}=char(quran_table{ii,3});
%     newStruct=setfield(newStruct,,curVar);
end


%%
strfind(quran_array{1}','Entirely Merciful')
strfind(quran_array{1}','Especially Merciful')
